# Wazuh App Copyright (C) 2020 Wazuh Inc. (License GPLv2)
version: '2'

services:
  wazuh:
    image: wazuh/wazuh:3.12.3_7.6.2
    hostname: wazuh-manager
    restart: always
    ports:
      - "1514:1514/udp"
      - "1515:1515"
      - "514:514/udp"
      - "55000:55000"

  elasticsearch:
    image: wazuh/wazuh-elasticsearch:3.12.3_7.6.2
    hostname: elasticsearch
    restart: always
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - ELASTIC_CLUSTER=true
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 2g

  kibana:
    image: wazuh/wazuh-kibana:3.12.3_7.6.2
    hostname: kibana
    restart: always
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
      - wazuh:wazuh

  nginx:
    image: k-oguma/wazuh-nginx:3.12.3_7.6.2_k1
    hostname: nginx
    restart: always
    environment:
      - NGINX_PORT=8080
      # Internal access via SSL termination on OAuth2_proxy.
      - NGINX_URL_SCHEME=http
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    depends_on:
      - kibana
    links:
      - kibana:kibana

volumes:
  wazuh_datastore:
    driver_opts:
      type: none
      device: /srv/docker-volumes/wazuh
      o: bind
  elasticsearch_datastore:
    driver_opts:
      type: none
      device: /srv/docker-volumes/elasticsearch
      o: bind

