name: wazuh-docker-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ktykogm
          image_name: wazuh
          image_tag: 3.12.3_7.6.2_k2
          push_image_and_stages: false
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ktykogm
          image_name: wazuh-nginx
          image_tag: 3.12.3_7.6.2_k1
          push_image_and_stages: false
      - name: Run a make all
        shell: bash
        run: make all
