name: wazuh-docker-ci

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build of host runner
        shell: bash
        run: |
          apt update -y
          apt install grep
          apt upgrade bash
      - name: Run a make all
        shell: bash
        run: make all
